services:
  - type: web
    name: kotak-api-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: CONSUMER_KEY
        value: your_consumer_key_here
      - key: CONSUMER_SECRET
        value: your_consumer_secret_here
